### ISSUE TITLE
Bug in FormMath

### ISSUE THREAD

**Issue by fgrub** [jlfaucher/FormMath#2]
Hi,
your FormMath is great, but there's a bug with some expressions.

Examples (after loading "mulisp mumathfm.sys"):
2^(1/2); is ok
(1/2)^(1/2); produces an error!
This happens for every expression a^(1/2) where a is of the form (x/y).

The strange thing is, that if you press C (Continue) after the error, you'll nevertheless get the correct result.
I hope you can fix this bug, because this 2D output of your muMathFM is very nice.

PS: it happens for every expression (a/b)^(c/d), if b,c and d are numbers!

**Comment by jlfaucher** [comment]
Thanks for reporting!

Fixed by overriding the default QUOTRAP with
FUNCTION QUOTRAP (LEX1), FIRST(LEX1) * SECOND(LEX1)^-1 ENDFUN$

mumathfm.sys updated.

**Comment by fgrub** [comment]
Yep, now it's working - thanks!
